import type { Metadata } from "next";
import { PageIntro } from "@/components/ui";
export const metadata: Metadata = {title: "Data sources & attribution"};
const sources = [
  {name:"nflverse officials & team history",type:"EXPECTED PERFORMANCE & REFEREES",description:"Accepted penalty totals, historical box scores, schedules and head-referee assignments support expected-versus-actual comparisons. Conflicting referee assignments are excluded; team/referee records include sample counts.",href:"https://nflreadr.nflverse.com/reference/load_officials.html",link:"Officials data documentation",note:"CC BY 4.0: nflverse / nflfastR; schedules additionally credit Lee Sharpe. Frozen source bytes, joins, transformations and exclusions are documented in the public repository."},
  {name:"nflverse / nflreadr", type:"SCHEDULES & PLAY-BY-PLAY", description:"Game schedules, play records, and historical data power the archive. Clean data and raw postgame builds have different availability. Reports identify the snapshots actually used.", href:"https://nflreadr.nflverse.com/articles/nflverse_data_schedule.html", link:"Availability & update schedule", note:"Dataset rights are separate from package licenses. Terms and provenance are recorded with snapshots."},
  {name:"nflfastR", type:"EXPECTED POINTS & WIN PROBABILITY", description:"Established state-based calculations provide context. Reports identify their model family and state assumptions. Unsupported rule-era states remain unavailable.", href:"https://www.nflfastr.com/", link:"nflfastR documentation", note:"Observed WPA is context, not an estimate of penalty or error-attributable impact."},
  {name:"nfl4th", type:"FOURTH-DOWN DECISIONS", description:"Fourth-down analysis compares expected outcomes of valid actions. Support depends on verified model semantics and validation of the applicable rule era.", href:"https://www.nfl4th.com/", link:"nfl4th documentation", note:"Model records identify the exact implementation and validation status."},
  {name:"FTN Data via nflverse", type:"MANUAL EXECUTION CHARTING", description:"Charting is available from 2022 onward and can be delayed or partial. Joins use documented game/play IDs; field-specific coverage stays visible.", href:"https://nflreadr.nflverse.com/reference/load_ftn_charting.html", link:"FTN loader & attribution", note:"FTN charting carries CC BY-SA 4.0. Attribution, license links, modification notices, and applicable share-alike terms must be preserved."},
];
export default function Sources() { return <><PageIntro eyebrow="PROVENANCE & CREDIT" title="The sources behind the record."><p>Data has a source, a timestamp, and limits. Reports show which version was used and what it can support.</p></PageIntro><div className="source-grid">{sources.map(source => <article key={source.name} className="source-card"><p className="eyebrow">{source.type}</p><h2>{source.name}</h2><p>{source.description}</p><a href={source.href} target="_blank" rel="noreferrer">{source.link} ↗</a><div className="source-note">{source.note}</div></article>)}</div><article className="prose source-policy"><h2>Attribution and use</h2><p>FTN charting: <a href="https://ftnfantasy.com/stats/sports-data" target="_blank" rel="noreferrer">FTN Data</a> via nflverse, under <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">Creative Commons Attribution-ShareAlike 4.0</a>. Counts and annotations may be filtered, joined, and summarized from source data; they do not imply FTN endorsement.</p><p>Software licenses do not automatically license accessed datasets. No league logos, proprietary grades, or video are required. Review-evidence links do not grant permission to republish media.</p><h2>Freshness is observed, not promised</h2><p>FTN documentation describes charting within 48 hours; nflverse refreshes four times daily in season. Upstream timing varies. Statistics can change after initial publication. Report timestamps describe the actual record rather than a promised deadline.</p><p className="small muted">Source documentation checked September 23, 2026. DATA_SOURCES.md in the repository contains verification details and access limitations. Individual snapshots provide actual retrieval times.</p></article></>; }
