import { listGames } from "@under-review/core/repository";
import { EmptyState, GameCard, Unavailable } from "@/components/ui";
import { gameView, teams } from "@/lib/presentation";
export const dynamic = "force-dynamic";
export default async function Home({searchParams}: {searchParams: Promise<Record<string, string | string[] | undefined>>}) {
  const query = await searchParams; const seasonValue = Number(query.season); const season = Number.isInteger(seasonValue) && seasonValue >= 1999 && seasonValue <= 2100 ? seasonValue : 2026;
  const weekValue = Number(query.week); let week = Number.isInteger(weekValue) && weekValue >= 1 && weekValue <= 22 ? weekValue : undefined;
  const team = typeof query.team === "string" && teams.includes(query.team) ? query.team : undefined;
  let games: Awaited<ReturnType<typeof listGames>> = []; let unavailable = false;
  try { games = (await listGames({season, week, team})).filter(game => game.revisionNumber !== null); } catch { unavailable = true; }
  if (query.week === undefined && games.length) {week = Math.max(...games.map(game => game.week)); games = games.filter(game => game.week === week);}
  return <><section className="home-intro"><div><p className="eyebrow"><span className="accent-line"/>NFL / {season} SEASON</p><h1>Beyond the<br/><span>final score.</span></h1><p>The calls. The choices. The breaks. <br/>Postgame analysis with an inspectable record.</p></div><div className="intro-aside"><span className="issue-number">01 — THE RECORD</span><p>What changed the game?<br/><strong>Start with the evidence.</strong></p><span>Impact and correctness are separate questions.</span></div></section><section className="archive-section" aria-labelledby="archive-title"><div className="section-heading"><div><p className="eyebrow">THE GAME FILES</p><h2 id="archive-title">Postgame reports <span className="count">{games.length}</span></h2></div><span className="section-caption">Coverage and freshness shown on every report.</span></div><form className="filters" action="/"><label>Season<select name="season" defaultValue={season}>{Array.from({length: 28}, (_, i) => 2026-i).map(y => <option key={y} value={y}>{y}</option>)}</select></label><label>Week<select name="week" defaultValue={week || ""}><option value="">All weeks</option>{Array.from({length: 22}, (_, i) => i+1).map(w => <option key={w} value={w}>Week {w}</option>)}</select></label><label>Team<select name="team" defaultValue={team || ""}><option value="">All teams</option>{teams.map(t => <option key={t}>{t}</option>)}</select></label><button className="button dark" type="submit">Apply filters <span aria-hidden="true">→</span></button><a className="clear-filter" href="/">Reset</a></form>{unavailable ? <Unavailable/> : games.length ? <div className="game-grid">{games.map(game => <GameCard key={gameView(game).id} game={game}/>)}</div> : <EmptyState title="The next report starts with real data.">No game reports match these filters. Validated games will appear here as they are processed.<br/>No placeholder scores. No invented findings.</EmptyState>}</section><section className="editorial-strip"><div><span className="strip-number">01</span><h3>Measure the impact.</h3><p>A ruling can change the game without being wrong.</p></div><div><span className="strip-number">02</span><h3>Show the evidence.</h3><p>Every finding links to its plays, inputs, and assumptions.</p></div><div><span className="strip-number">03</span><h3>Keep the uncertainty.</h3><p>Missing data stays missing. Unusual does not mean rigged.</p></div></section></>;
}
