import { describe,it,expect } from 'vitest';
import type { Review } from '../packages/core/src/contracts.js';
import { currentReviews,reviewCoverageStatus,reviewSummary } from '../packages/core/src/repository.js';
import { reviewInputSchema } from '../packages/core/src/reviews.js';
const baseline:Review={id:'review-1',eventId:'synthetic-game:10',playId:'10',reviewer:'synthetic-reviewer',status:'supported',ruleSeason:2026,ruleReference:'Synthetic rule reference',evidenceUrl:'https://example.invalid/synthetic-evidence',rationale:'Explicitly synthetic scope-policy test.',confidence:'medium',scope:'Only the catch ruling on synthetic play 10.',approved:false,stale:false,createdAt:'2026-09-20T10:00:00.000Z',replayCorrected:false};
describe('explicit review-scope completion',()=>{
 it('requires administrator approval before declaring a scope reviewed',()=>{const review={...baseline,scopeComplete:true};expect(reviewCoverageStatus([review])).toBe('partially_reviewed');expect(reviewCoverageStatus([{...review,approved:true}])).toBe('reviewed_within_scope');});
 it('preserves absent completion flags on historical snapshots as incomplete',()=>{expect(reviewCoverageStatus([{...baseline,approved:true}])).toBe('partially_reviewed');expect(reviewSummary([baseline])).not.toContain('Reviewed within these explicitly completed');});
 it('names completed scopes without claiming whole-game coverage or correctness',()=>{const summary=reviewSummary([{...baseline,scopeComplete:true,approved:true,status:'insufficient_evidence'}]);expect(summary).toContain(JSON.stringify(baseline.scope));expect(summary).toContain('not whole-game coverage');expect(summary).toContain('0 events have approved likely-incorrect findings');});
 it('uses the newest assessment per reviewer and retains independent reviewers',()=>{const newer={...baseline,id:'review-2',status:'debatable',createdAt:'2026-09-20T11:00:00.000Z'};const second={...baseline,id:'review-3',reviewer:'independent-reviewer'};expect(currentReviews([baseline,second,newer]).map(review=>review.id)).toEqual(['review-2','review-3']);});
 it('does not resurrect an older completed approval when its replacement is stale',()=>{const prior={...baseline,scopeComplete:true,approved:true};const stale={...prior,id:'review-2',createdAt:'2026-09-20T11:00:00.000Z',stale:true};expect(currentReviews([prior,stale])).toEqual([]);expect(reviewCoverageStatus([prior,stale])).toBe('not_reviewed');expect(reviewSummary([prior,stale])).toBe('Officiating correctness: not reviewed.');});
 it('does not mutate the immutable input snapshot while selecting current reviews',()=>{const newer={...baseline,id:'review-2',createdAt:'2026-09-20T11:00:00.000Z'};const snapshot=[baseline,newer];const before=structuredClone(snapshot);currentReviews(snapshot);expect(snapshot).toEqual(before);});
 it('rejects a completion attestation paired with not reviewed',()=>{const input={...baseline,gameId:'synthetic-game',scopeComplete:true,status:'not_reviewed'};expect(reviewInputSchema.safeParse(input).success).toBe(false);expect(reviewInputSchema.safeParse({...input,status:'supported'}).success).toBe(true);});
});
