import type { Metadata } from "next";
import { getOperationalStatus } from "@under-review/core/repository";
import { EmptyState, PageIntro, Status } from "@/components/ui";
import { dateTime } from "@/lib/presentation";
export const dynamic = "force-dynamic";
export const metadata: Metadata = {title: "System status"};
export default async function SystemStatus() {
  const status=await getOperationalStatus();
  const workerRecent = status.workerLastSeen && Date.now()-new Date(status.workerLastSeen).getTime() < 300000;
  return <><PageIntro eyebrow="REPORT UPDATES" title="Are automatic reports running?"><p>Games are picked up after they finish and final data is available. Reports update again when the source data improves.</p></PageIntro>
    <div className="status-grid"><article><span className="eyebrow">AUTOMATIC GAME ANALYSIS</span><h2>{workerRecent && status.database ? "Automatic reports running" : "Updates may be delayed"}</h2><p>{workerRecent ? "The analysis service is active." : "We have not received a recent check-in from the analysis service."}</p><p className="small">Last check-in: {dateTime(status.workerLastSeen)}</p></article><article><span className="eyebrow">SAVED GAME REPORTS</span><h2>{status.database ? "Available" : "Temporarily unavailable"}</h2><p>{status.database ? "Saved reports can be read while new games are processed." : "The report database is not responding. Please try again shortly."}</p></article><article><span className="eyebrow">WHEN A GAME ENDS</span><h2>Final data comes first</h2><p>Analysis starts after the provider publishes complete final-game data. A provider delay or a game already being processed can delay the next report.</p></article></div>
    <section className="report-section"><div className="section-heading"><h2>Latest data updates</h2></div>{status.sources.length ? <div className="table-scroll"><table><thead><tr><th>Data source</th><th>Last received</th></tr></thead><tbody>{status.sources.map(source=><tr key={source.provider}><td>{source.provider}</td><td>{dateTime(source.retrievedAt)}</td></tr>)}</tbody></table></div> : <EmptyState title="Waiting for the first data update" compact>Updates appear here after data has been received successfully.</EmptyState>}</section>
    <section className="report-section"><details className="report-disclosure"><summary><span><strong>Processing activity</strong><span className="disclosure-description">Background tasks and separate social-posting settings.</span></span><span aria-hidden="true">+</span></summary><div className="disclosure-body">{status.jobs.length ? <div className="job-counts">{status.jobs.map(job=><div key={job.status}><Status value={job.status}/><strong>{job.count}</strong></div>)}</div> : <p className="muted">No processing activity is available.</p>}<p className="section-explanation" style={{marginTop:24}}>Social posts: <strong>{status.publishing.killSwitch || status.publishing.mode === "off" ? "Off" : status.publishing.mode === "automatic" ? "Automatic" : "Drafts only"}</strong>. This controls posts to social media; it does not pause automatic game analysis or reports on this website.</p></div></details></section>
  </>;
}
