root <- Sys.getenv("ANALYTICS_ROOT", "analytics")
source(file.path(root, "R/common.R")); source(file.path(root, "R/rarity.R"))
dir <- tempfile("rarity-test-"); dir.create(dir)
m <- metric("x", "kicking", "Residual", "SEA", 100, "points", model = "known-hash")
key <- paste(rarity_key(m), "1", sep = "|")
reference <- list(categories = list(list(key = key, gameCount = 200L, maximumSeason = 2025L, referencePeriod = "2024–2025", values = as.list(1:200), comparison = "Synthetic contract fixture")))
write_json(reference, file.path(dir, "category-reference.json"))
run <- function(metric = m, season = 2026) add_rarity(list(metric), list(season = season), dir)[[1]]$rarity
stopifnot(run()$status == "supported", run()$percentile == 50, run(season = 2025)$reasonCode == "reference_not_chronologically_prior")
tail <- m; tail$value <- 1000; stopifnot(run(tail)$reasonCode == "insufficient_tail_support")
partial <- m; partial$coverage$modeled <- 0; stopifnot(run(partial)$reasonCode == "incomplete_or_no_opportunities")
other <- m; other$modelVersion <- "changed-model"; stopifnot(run(other)$reasonCode == "comparable_reference_unavailable")
reference$categories[[1]]$gameCount <- 199L; write_json(reference, file.path(dir, "category-reference.json"))
stopifnot(run()$reasonCode == "insufficient_reference_games")
real <- jsonlite::read_json(file.path(root, "models/category-reference.json"))
stopifnot(length(real$categories) > 0, any(vapply(real$categories, function(r) r$gameCount >= 200, logical(1))))
for (r in real$categories) stopifnot(length(unique(unlist(r$gameIds))) == r$gameCount, length(r$values) == r$gameCount)
actual <- jsonlite::read_json(file.path(root, "tests/output-2026_01_NE_SEA.json"))
actual$metrics <- add_rarity(actual$metrics, list(season = 2026), file.path(root, "models"))
stopifnot(any(vapply(actual$metrics, function(m) m$rarity$status == "supported", logical(1))))
write_json(actual, file.path(root, "tests/output-rarity-2026_01_NE_SEA.json"))
message("Rarity chronological, coverage, model, sample-size and tail gates passed.")
