import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getReport, getGame, currentReviews } from "@under-review/core/repository";
import { log, safeError } from "@under-review/core/config";
import type { GameReport, EvidenceEvent } from "@under-review/core/contracts";
import { EmptyState, Evidence, Freshness, MetricValue, MetricRarity, Status, Unavailable, WpTimeline } from "@/components/ui";
import { categories, dataMaturity, dateTime, human, humanReview, safeLink, teamName } from "@/lib/presentation";
import { RevealEvent } from "@/components/reveal-event";
import { SourcePlays } from "@/components/source-plays";
import { GameAnomalyAudit, NeedsReview, GameVerdict } from "@/components/game-audit";

export async function generateMetadata({params}: {params: Promise<{gameId: string}>}): Promise<Metadata> {
  const {gameId} = await params; const [,week,away,home] = gameId.split("_");
  return {title: away && home ? `${teamName(away)} at ${teamName(home)} — Week ${Number(week)}` : "Game report", description:"Was this an unusual win? A clear game verdict, historical comparisons, and the key plays worth a closer look."};
}
export default async function ReportPage({params, searchParams}: {params: Promise<{gameId: string}>; searchParams: Promise<{revision?: string}>}) {
  const {gameId} = await params; const query = await searchParams; const requested = Number(query.revision); const revisionNumber = Number.isInteger(requested) && requested > 0 ? requested : undefined;
  let report: GameReport | null;
  try { report = await getReport(gameId, revisionNumber); } catch(error) { log('web.report.failed',{gameId,error:safeError(error)}); return <><Link prefetch={false} className="back-link" href="/">← All game reports</Link><Unavailable/></>; }
  if (!report) {
    if (revisionNumber) notFound();
    let awaiting; try {awaiting = await getGame(gameId);} catch {return <Unavailable/>;}
    if (!awaiting) notFound();
    return <><div className="report-topline"><Link prefetch={false} className="back-link" href="/">← All game reports</Link><span>{awaiting.season} / WEEK {awaiting.week}</span></div><div className="page-intro"><p className="eyebrow">AUTOMATIC POSTGAME REPORT</p><h1>{teamName(awaiting.awayTeam)} at {teamName(awaiting.homeTeam)}</h1><Status value="awaiting_data" label="Waiting for final game data"/></div><EmptyState title="This game will be analyzed automatically">The report starts once the game ends and complete final-game data is available. Provider delays can take time; you do not need to request a review or press a button.<br/><a href="/status">Check report updates →</a></EmptyState></>;
  }
  const {game, revision, history, reviews} = report; const {analysis} = revision;
  const maturity = dataMaturity(revision.statisticalStatus); const review = humanReview(revision.reviewStatus);
  const latestRevision = Math.max(...history.map(item=>item.number), revision.number);
  const sourcePlays=[...analysis.timeline];
  for(const candidate of analysis.gameAudit?.reviewCandidates??[])if(!sourcePlays.some(play=>play.playId===candidate.playId))sourcePlays.push({playId:candidate.playId,quarter:candidate.quarter,clock:candidate.clock,description:candidate.description,homeWp:null});
  const localImpact=new Map<string,number>();
  for(const metric of analysis.metrics){if(metric.status==='supported'&&metric.unit==='wp_delta'&&metric.value!==null&&metric.eventIds.length===1){const id=metric.eventIds[0];localImpact.set(id,Math.max(localImpact.get(id)??0,Math.abs(metric.value)));}}
  const prioritizedEvents=[...analysis.events].sort((a,b)=>(localImpact.get(b.id)??-1)-(localImpact.get(a.id)??-1));
  const renderEvent=(event:EvidenceEvent)=><Evidence key={event.id} event={event} metrics={analysis.metrics.filter(metric=>metric.eventIds.includes(event.id))} reviews={reviews.filter(review=>review.eventId===event.id)}/>;
  return <>
    <RevealEvent/>
    <div className="report-topline"><Link prefetch={false} className="back-link" href="/">← All game reports</Link><span>{game.season} / WEEK {game.week} / {game.gameType === "REG" ? "REGULAR SEASON" : "POSTSEASON"}</span></div>
    {revision.number < latestRevision && <aside className="older-revision-notice">You are viewing an older report from {dateTime(revision.createdAt)}. <Link prefetch={false} href={`/games/${encodeURIComponent(game.id)}`}>See the latest analysis →</Link></aside>}
    <section className="report-header consumer-report-header" aria-labelledby="matchup-title">
      <div><p className="eyebrow">FINAL SCORE</p><h1 id="matchup-title">{teamName(game.awayTeam)} <span>at</span> {teamName(game.homeTeam)}</h1><div className="matchup-score" aria-label={`${teamName(game.awayTeam)} ${game.awayScore}, ${teamName(game.homeTeam)} ${game.homeScore}`}><span>{game.awayTeam} <strong>{game.awayScore ?? "—"}</strong></span><span className="score-separator">—</span><span>{game.homeTeam} <strong>{game.homeScore ?? "—"}</strong></span></div></div>
      <div className="report-edition"><span className="analysis-complete">✓ Automated analysis complete</span><Freshness value={revision.createdAt} label="Updated"/><span className="edition-number">Report version {revision.number}</span></div>
    </section>
    <GameVerdict audit={analysis.gameAudit}/>
    <nav className="report-jump" aria-label="Report sections"><a href="#game-audit">Why this result</a><a href="#needs-review">Key plays</a><a href="#timeline">Game momentum</a><a href="#categories">Detailed analysis</a><a href="#provenance">Data & updates</a></nav>
    <GameAnomalyAudit audit={analysis.gameAudit} game={game} fallbackSummary={revision.summary}/>
    <NeedsReview audit={analysis.gameAudit}/>
    <section id="timeline" className="report-section"><div className="section-heading"><div><p className="eyebrow">HOW THE GAME MOVED</p><h2>Game momentum</h2></div></div><p className="section-explanation">The model’s estimate of each team’s chance to win as the game unfolded.</p><WpTimeline points={analysis.timeline} home={game.homeTeam} away={game.awayTeam}/><p className="chart-footnote">A swing includes everything that happened on the play. It does not isolate the effect of an officiating decision.</p></section>
    <section id="categories" className="report-section"><details className="report-disclosure"><summary><span><span className="eyebrow">DIG INTO THE NUMBERS</span><strong>Detailed analysis by category</strong><span className="disclosure-description">Officiating impact, coaching, turnovers, kicking, and more.</span></span><span aria-hidden="true">+</span></summary><div className="disclosure-body"><p className="section-explanation">Each calculation answers a specific question. Categories with missing data do not cancel the completed game analysis above.</p><div className="category-grid">{categories.map((category,index)=>{
      const metrics=analysis.metrics.filter(metric=>metric.category===category.id);const coverage=analysis.coverage.find(item=>item.category===category.id);
      return <article className="category-panel" key={category.id}><div className="category-title"><span>{String(index+1).padStart(2,"0")}</span><h3>{category.title}</h3></div><p className="category-explainer">{category.note}</p>{category.id === "reviewed_errors" ? <><p><strong>{review.label}</strong></p><p className="small">{reviews.length ? `${currentReviews(reviews).filter(item=>item.approved).length} current, approved play reviews. See the event evidence for their scope and reasoning.` : review.detail}</p></> : metrics.length ? <div className="metrics">{metrics.map(metric=><details className="metric-item" key={metric.id}><summary><span><span className="metric-team">{metric.team || "GAME"}</span><strong>{human(metric.name)}</strong></span><MetricValue metric={metric}/></summary><div className="metric-detail"><Status value={metric.status}/><MetricRarity metric={metric}/>{metric.reasonCode && <p>{human(metric.reasonCode)}</p>}<p>{metric.coverage.modeled} of {metric.coverage.eligible} eligible opportunities modeled.</p>{metric.assumptions.length>0 && <ul>{metric.assumptions.map((assumption,i)=><li key={i}>{assumption}</li>)}</ul>}<p className="small">Model: {metric.modelVersion}</p>{metric.eventIds.length>0 && <div className="event-links">{metric.eventIds.map(id=><a key={id} href={`#event-${encodeURIComponent(id)}`}>Event {id}</a>)}</div>}</div></details>)}</div> : <div className="category-missing"><strong>No result available</strong><p>{coverage?.reason || "The source data does not support this calculation for this game."}</p></div>}</article>;
    })}</div></div></details></section>
    <SourcePlays plays={sourcePlays} home={game.homeTeam}/>
    <section id="evidence" className="report-section"><details className="report-disclosure"><summary><span><span className="eyebrow">CHECK THE CALCULATIONS</span><strong>Play-by-play model evidence <span className="count">{analysis.events.length}</span></strong><span className="disclosure-description">Inspect assumptions and human reviews behind each event.</span></span><span aria-hidden="true">+</span></summary><div className="disclosure-body">{analysis.events.length ? <><p className="small muted">{localImpact.size ? "Largest estimated individual impacts appear first. This order does not determine whether a call was right or wrong." : "Events appear in the order recorded by the data source."}</p><div className="evidence-list">{prioritizedEvents.slice(0,12).map(renderEvent)}</div>{prioritizedEvents.length>12 && <details className="more-evidence"><summary>Show the remaining {prioritizedEvents.length-12} recorded events</summary><div className="evidence-list">{prioritizedEvents.slice(12).map(renderEvent)}</div></details>}</> : <EmptyState title="No modeled events available" compact>The game summary above is still available. There are no event-level calculations to inspect.</EmptyState>}</div></details></section>
    <section id="provenance" className="report-section"><details className="report-disclosure"><summary><span><span className="eyebrow">ABOUT THIS REPORT</span><strong>Data, updates & human review</strong><span className="disclosure-description">{maturity.label}. {review.label}.</span></span><span aria-hidden="true">+</span></summary><div className="disclosure-body">
      <div className="report-status-explained"><article><h3>Automatic analysis</h3><strong>Complete</strong><p>This report was generated automatically. It is checked again as updated postgame data becomes available.</p></article><article><h3>Source data</h3><strong>{maturity.label}</strong><p>{maturity.detail}</p></article><article><h3>Human officiating review</h3><strong>{review.label}</strong><p>{review.detail}</p></article></div>
      {analysis.warnings.length>0 && <details className="report-notes"><summary>Data limitations and calculation notes ({analysis.warnings.length})</summary><ul>{analysis.warnings.map((warning,i)=><li key={i}>{warning}</li>)}</ul></details>}
      <div className="provenance"><div><h2>Data sources</h2>{revision.sourceSnapshots.length ? revision.sourceSnapshots.map(source=><article className="source-record" key={source.id}><h3>{source.provider}</h3><p>{safeLink(source.url) ? <a href={safeLink(source.url)} target="_blank" rel="noreferrer">View original data ↗</a> : "Source URL unavailable"}</p><p className="small">Retrieved {dateTime(source.retrievedAt)}<br/>License: {source.license}</p><details className="source-checksum"><summary>Verify this snapshot</summary><code className="checksum">SHA-256 {source.checksum}</code></details></article>) : <p className="muted">No source snapshot metadata is available.</p>}<details className="report-notes"><summary>Model versions and technical record</summary>{analysis.models.map(model=><div key={`${model.id}-${model.version}`} className="model-record"><strong>{model.id} / {model.version}</strong><p>Training window: {model.trainingWindow || "Not established; retrospective evaluation is not claimed to be leakage-free."}</p>{model.notes && <p>{model.notes}</p>}</div>)}<p className="small">Analysis input hash: <code className="checksum">{revision.inputHash}</code></p></details></div><div><h2>Report updates</h2><p className="small">Each saved version stays available so you can see what changed.</p><ol className="revision-list">{history.map(item=><li key={item.id}><Link prefetch={false} href={`/games/${encodeURIComponent(game.id)}?revision=${item.number}`} aria-current={item.number===revision.number ? "page" : undefined}>Version {item.number} {item.number===latestRevision ? "· Latest" : ""} <span>↗</span></Link><p><strong>{dataMaturity(item.statisticalStatus).label}</strong></p><p>{item.changeSummary}</p><time>{dateTime(item.createdAt)}</time></li>)}</ol></div></div>
    </div></details></section>
  </>;
}
