import Link from "next/link";
import type { ReactNode } from "react";
import type { GameCard as CardData, Metric, EvidenceEvent, Review, AnalysisResult } from "@under-review/core/contracts";
import { dateTime, first, gameView, human, num, record, records, safeLink, statusTone, str, type RecordValue } from "@/lib/presentation";

export function Status({value, label}: {value: unknown; label?: string}) { return <span className={`status ${statusTone(value)}`}><span aria-hidden="true" />{label || human(value)}</span>; }
export function PageIntro({eyebrow, title, children}: {eyebrow: string; title: string; children?: ReactNode}) { return <div className="page-intro"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{children && <div className="intro-copy">{children}</div>}</div>; }
export function EmptyState({title, children, compact = false}: {title: string; children: ReactNode; compact?: boolean}) { return <div className={`empty-state ${compact ? "compact" : ""}`}><span className="empty-mark" aria-hidden="true">∅</span><h2>{title}</h2><div>{children}</div></div>; }
export function Unavailable({children}: {children?: ReactNode}) { return <div className="notice"><span className="notice-icon" aria-hidden="true">!</span><div><strong>Data connection unavailable</strong><p>{children || "The report archive is temporarily unavailable. No results have been substituted. Please try again shortly."}</p></div></div>; }
export function GameCard({game}: {game: CardData}) {
  const g = {id: game.id, home: game.homeTeam, away: game.awayTeam, homeScore: game.homeScore, awayScore: game.awayScore, week: game.week, season: game.season, statistical: game.statisticalStatus, review: game.reviewStatus, finding: game.finding};
  return <article className="game-card"><div className="card-top"><span>WEEK {g.week || "—"} <span className="muted">/ {g.season}</span></span><Status value={g.statistical} /></div><Link className="scoreboard-link" href={`/games/${encodeURIComponent(g.id)}`} aria-label={`Read ${g.away} at ${g.home} report`}><div className="score-row"><span className="team-monogram">{g.away.slice(0, 1)}</span><span>{g.away}</span><strong>{g.awayScore ?? "—"}</strong></div><div className="score-row"><span className="team-monogram home">{g.home.slice(0, 1)}</span><span>{g.home}</span><strong>{g.homeScore ?? "—"}</strong></div></Link><div className="card-finding"><span className="eyebrow">IN THE RECORD</span><p>{g.finding || "Supported findings appear after the game data passes validation."}</p></div><div className="card-bottom"><span>{human(g.review)}</span><Link href={`/games/${encodeURIComponent(g.id)}`}>Open report <span aria-hidden="true">↗</span></Link></div></article>;
}
export function Freshness({value, label = "Last processed"}: {value: unknown; label?: string}) { return <span className="freshness">{label} <time>{dateTime(value)}</time></span>; }
export function DefinitionRows({value}: {value: unknown}) {
  const data = record(value); const items = Object.entries(data).filter(([, v]) => v !== undefined);
  return items.length ? <dl className="definition-rows">{items.map(([key, val]) => <div key={key}><dt>{human(key)}</dt><dd>{val === null ? "Unavailable" : typeof val === "object" ? <code>{JSON.stringify(val)}</code> : String(val)}</dd></div>)}</dl> : <p className="muted">State not available.</p>;
}
export function Evidence({event, metrics, reviews}: {event: EvidenceEvent; metrics: Metric[]; reviews: Review[]}) {
  return <details className="evidence" id={`event-${event.id}`}><summary><span className="event-time">{event.quarter ? `Q${event.quarter}` : "PLAY"}<strong>{event.clock || event.playId}</strong></span><span className="event-title"><strong>{human(event.kind, "Recorded event")}{event.team ? ` · ${event.team}` : ""}</strong><span>{event.description}</span></span><span className="expand-sign" aria-hidden="true">+</span></summary><div className="evidence-body"><div className="evidence-meta"><Status value={event.reviewStatus}/><span>Play {event.playId}</span><a href={`#event-${event.id}`}>Link to event</a></div>{event.notes && event.notes.length > 0 && <div className="assumptions"><h4>Event notes</h4><ul>{event.notes.map((note,index) => <li key={index}>{note}</li>)}</ul></div>}{metrics.length ? metrics.map(metric => <section className="event-metric" key={metric.id}><h4>{human(metric.name)} <span className="muted">{metric.team}</span></h4><p><MetricValue metric={metric}/> <Status value={metric.status}/></p><div className="state-pair"><section><h4>Actual state</h4><DefinitionRows value={metric.actualState}/></section><section><h4>Supported alternative</h4>{metric.alternativeState ? <DefinitionRows value={metric.alternativeState}/> : <p className="muted">No supported alternative state. Observed play impact is not an estimate of error cost.</p>}</section></div>{metric.assumptions.length > 0 && <div className="assumptions"><h4>Assumptions</h4><ul>{metric.assumptions.map((item, i) => <li key={i}>{item}</li>)}</ul></div>}<p className="small muted">Model {metric.modelVersion} · {metric.coverage.modeled}/{metric.coverage.eligible} eligible events modeled</p></section>) : <p className="muted">This event has no supported modeled impact. Its observed result alone does not establish the cost of an error.</p>}{reviews.map(review => <div className="review-note" key={review.id}><Status value={review.status}/>{review.stale && <Status value="stale" label="Review predates corrected inputs"/>}<p>{review.rationale}</p><p className="small">{review.reviewer} · {review.confidence} confidence · {review.approved ? "Approved" : "Not approved"}{review.replayCorrected ? " · Corrected by replay" : ""}</p><p className="small">Rule {review.ruleSeason}: {review.ruleReference}<br/>Review scope: {review.scope}<br/>Scope completion: {review.scopeComplete ? review.approved && !review.stale ? "Attested and administrator-approved for this stated scope only." : "Reviewer-attested; not a current approved completion." : "Not attested."}</p>{safeLink(review.evidenceUrl) && <a href={safeLink(review.evidenceUrl)} target="_blank" rel="noreferrer">Review evidence ↗</a>}</div>)}</div></details>;
}
export function MetricValue({metric}: {metric: Metric}) {
  if (metric.value === null || metric.status === "unavailable") return <span className="metric-unavailable">Unavailable</span>;
  const wp = ["wp", "probability", "wp_delta"].includes(metric.unit); const value = wp ? metric.value * 100 : metric.value;
  return <span className="metric-value">{new Intl.NumberFormat("en-US", {maximumFractionDigits: Number.isInteger(value) ? 0 : 2, signDisplay: "auto"}).format(value)} <small>{wp ? "pp" : metric.unit.replace(/_/g, " ")}{metric.status === "experimental" ? " · experimental" : ""}</small></span>;
}
export function MetricRarity({metric}: {metric: Metric}) {
  const rarity=metric.rarity;if(!rarity)return null;
  const supported=metric.status==='supported'&&rarity.status==='supported'&&rarity.percentile!==null;
  const percentile=rarity.percentile===null?null:Math.round(rarity.percentile);
  const suffix=percentile!==null&&percentile%100>=11&&percentile%100<=13?'th':({1:'st',2:'nd',3:'rd'} as Record<number,string>)[(percentile??0)%10]||'th';
  return <div className="rarity-record"><span className="eyebrow">HISTORICAL COMPARISON</span><strong>{supported?`${percentile}${suffix} percentile`:'Historical percentile unavailable'}</strong>{!supported&&<p>{human(rarity.reasonCode,'Reference coverage or model validation is insufficient.')}</p>}<p>{rarity.comparison}</p><p className="small muted">Reference: {rarity.referencePeriod} · {rarity.gameCount} games<br/>Model: {rarity.modelVersion}</p><code className="checksum">Reference SHA-256: {rarity.referenceChecksum}</code><p className="small muted">A measure of rarity in this comparison, not a probability of manipulation.</p></div>;
}
export function WpTimeline({points: raw, home, away}: {points: AnalysisResult["timeline"]; home: string; away: string}) {
  const points = raw.map((p, index) => ({index, probability: p.homeWp, play: p.playId, clock: p.clock || ""})).filter((p): p is {index: number; probability: number; play: string; clock: string} => p.probability !== null && p.probability >= 0 && p.probability <= 1);
  if (!points.length) return <EmptyState title="Timeline unavailable" compact>The report has no supported win-probability series yet.</EmptyState>;
  const line = points.map((p, index) => `${index === 0 || p.index !== points[index-1].index + 1 ? "M" : "L"}${44 + p.index / Math.max(raw.length - 1, 1) * 892},${24 + (1 - p.probability) * 180}`).join(" ");
  return <div className="wp-chart"><div className="chart-legend"><span><i />{home} win probability</span><span className="muted">Observed game states · {away} opponent</span></div><svg viewBox="0 0 960 235" role="img" aria-labelledby="wp-title wp-desc"><title id="wp-title">{home} win probability during the game</title><desc id="wp-desc">Observed probabilities from {points.length} game states. A table of the values follows. This chart does not attribute changes to officiating errors.</desc>{[0, .5, 1].map(v => <g key={v}><line x1="44" x2="936" y1={24 + (1-v)*180} y2={24+(1-v)*180} stroke="currentColor" opacity=".12" strokeDasharray={v === .5 ? "4 5" : undefined}/><text x="0" y={29+(1-v)*180} fill="currentColor" fontSize="11">{v*100}%</text></g>)}<path d={line} fill="none" stroke="var(--ink)" strokeWidth="2.6" vectorEffect="non-scaling-stroke"/><text x="44" y="228" fill="currentColor" fontSize="11">Game start</text><text x="878" y="228" fill="currentColor" fontSize="11">Game end</text></svg><details className="chart-table"><summary>View chart data ({points.length} states)</summary><div className="table-scroll"><table><caption className="sr-only">{home} observed win probability</caption><thead><tr><th>Play</th><th>Clock</th><th>{home} WP</th></tr></thead><tbody>{points.map(p => <tr key={p.index}><td>{p.play}</td><td>{p.clock || "—"}</td><td>{(p.probability*100).toFixed(1)}%</td></tr>)}</tbody></table></div></details></div>;
}
